version: 2
updates:
  # GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    assignees:
      - 'pandatix'
    groups:
      # init/autobuild/analyze must stay on the same version or CodeQL errors out
      codeql-action:
        patterns:
          - "github/codeql-action*"

  # Go module
  - package-ecosystem: 'gomod'
    directories:
      - '/'
    schedule:
      interval: 'weekly'
    assignees:
      - 'pandatix'
